### ISSUE TITLE
path.exists() is replaced by fs.exists()

### ISSUE THREAD

**Issue by markTreveil** [codecapers/AngularJS-FlowChart#14]
It seems that node.js (which I've never used) have removed path.exists() and replaced with fs.exists().

As as result the sample server fails to run when using the latest node.js download.  Changing the one reference in server.js rrom path.exists to fs.exists fixes this problem.

**Comment by ashleydavis** [comment]
Thanks for your feedback, I've fixed the code and updated the repo.
