### ISSUE TITLE
Keycodes for "a" and "ctrl" buttons

### ISSUE THREAD

**Issue by matthewha** [codecapers/AngularJS-FlowChart#15]
Hi,

The code as is does not allow you to enter "a" into the JSON model on the left and to select all nodes you must hold down "a" and then press "ctrl". This is due to the keycodes for "a" and "ctrl" in app.js being switched.

However, when the keycode values are swapped, pressing ctrl-a selects all the text on the LHS as well as selecting all nodes.

I have tested this in both Chrome and IE 11.

Cheers

**Comment by ashleydavis** [comment]
Thanks for letting me know. Would you like to become a contributor? Clone the repo, make the change and then submit a pull request.

**Comment by ashleydavis** [comment]
Fixed by pull request.
