### ISSUE TITLE
Change curved path into straight path

### ISSUE THREAD

**Issue by frostchick** [codecapers/AngularJS-FlowChart#17]
Hi,
How can i change the style of path from curved path into straight path and the path is auto avoid node drag section

**Comment by ashleydavis** [comment]
You would need to use an SVG curve to render it. Something like this: https://developer.mozilla.org/en-US/docs/Web/SVG/Tutorial/Paths

Then you would need to implement some kind of 'path finding' algorithm, similar to what is used in the game development industry, to navigate a path around nodes between the source and destination. 

If you come up with something, please fork and submit a pull request. Then you can be a contributor!

**Comment by frostchick** [comment]
it mean now the path is pass over node's section... i want to ask how to make the path of connection line avoid the node's section when i draw the chart :(...
P/S : sorry my english is not good ...

**Comment by ashleydavis** [comment]
I understand. What you want is something similar to "path finding" in game development. An algorithm that can find a path avoiding obstacles. Hopefully that helps you get a start on this. Please let me know if you figure something out.

**Comment by frostchick** [comment]
thank you... that's what i need
