### ISSUE TITLE
Dragging nodes in IE10

### ISSUE THREAD

**Issue by claud1nho** [codecapers/AngularJS-FlowChart#18]
Hi, 

when dragging nodes with the mouse in IE10 I get the Error
SVG4601: SVG Path data has incorrect format and could not be completely parsed

The problem and its solution is described here https://developer.mozilla.org/en-US/docs/Web/API/Window/scrollY.

So function 'translateCoordinates' in flowchart_directive.js should look like this:

    this.translateCoordinates = function(x, y, evt) {
		var svg_elem =  $element.get(0);
		var matrix = svg_elem.getScreenCTM();
		var point = svg_elem.createSVGPoint();
		//point.x = x - evt.view.scrollX;
		//point.y = y - evt.view.scrollY;
		point.x = x - evt.view.pageXOffset;
		point.y = y - evt.view.pageYOffset;
		return point.matrixTransform(matrix.inverse());
	};

**Comment by ashleydavis** [comment]
Please feel free to contribute the solution and submit a pull requests.
