### ISSUE TITLE
Make only output could be connected to input and 1 node only can connect with 1 other node.

### ISSUE THREAD

**Issue by frostchick** [codecapers/AngularJS-FlowChart#20]
i adready do follow this https://github.com/codecapers/AngularJS-FlowChart/commit/8d1b56406f5373a0073582737a57403d40b43f43 but notthing happen... the output still connect with another output and input can too...
And can we make 1 node only connect to 1 other node?.

**Comment by ashleydavis** [comment]
Yes you can do that. It's probably a simple addition. Please let me know how you solve it.

**Comment by frostchick** [comment]
here is my code :
