### ISSUE TITLE
Bower package repo reports 404 not found

### ISSUE THREAD

**Issue by ackdev** [codecapers/AngularJS-FlowChart#22]
bower install angular-flowchart
bower angular-flowchart#*   not-cached git://github.com/tobiasoberrauch/angular-flowchart.git#*
bower angular-flowchart#*      resolve git://github.com/tobiasoberrauch/angular-flowchart.git#*
bower angular-flowchart#*      ECMDERR Failed to execute "git ls-remote --tags --heads git://github.com/tobiasoberrauch/angular-flowchart.git", exit code of #128 fatal: remote error:    Repository not found.

**Comment by ashleydavis** [comment]
This isn't available on bower. It's not a general purpose UI control. It's just an example. Please clone or download it and modify it as you wish.
