### ISSUE TITLE
mouseCapture is not using explicit annotation

### ISSUE THREAD

**Issue by tawanda** [codecapers/AngularJS-FlowChart#23]
Hello

I get this error on angular 1.4.7

`function($scope, $element, $attrs, mouseCapture is not using explicit annotation and cannot be invoked in strict mode`

**Comment by ashleydavis** [comment]
Any idea how to fix it?

**Comment by tawanda** [comment]
yes, i fixed it and sent you a pull request

**Comment by ashleydavis** [comment]
I accepted your pull request. Thank!
