### ISSUE TITLE
How to get control on handleNodeClicked action

### ISSUE THREAD

**Issue by gs-jyenduri** [codecapers/AngularJS-FlowChart#27]
I want to override the handleNodeClicked action in my controller, how can I do that?

**Comment by ashleydavis** [comment]
Simply redefine the function to whatever you want. It's just JavaScript.

function MyController($scope, etc) {
     var flowChartViewModel = new ChartViewModel(...);
     flowChartViewMode.handleNodeClicked = function (node, ctrlKey) {
          // ... handle it however you want ...
     };
}

However I'd argue that the controller is wrong place for this code.

You should just redefine handleNodeClicked in the view-model to be whatever you want.
