### ISSUE TITLE
TypeErrors when using AngularJS-FlowChart in existing Angular app

### ISSUE THREAD

**Issue by Audace** [codecapers/AngularJS-FlowChart#28]
I’m running into some issues using it within the context of an existing angular app. Attached a screenshot of the errors I get below. I think it has something to do with scope as when I launch your repo, it works perfectly. However, when I include it within mine, I get errors and the chart gets the class ‘ng-isolate-scope’.

Nonetheless, the chart still populates but I can't drag anything around or change anything. The chartViewModel is also accessible via Angular scope from Chrome.

Here's a gist of my code: https://gist.github.com/Audace/98a7aab47a4531c107668991d7b7d783

Any idea what's happening or how to best debug?

Cheers,
Will

![screen shot 2016-07-09 at 10 21 32 am](https://cloud.githubusercontent.com/assets/3901743/16708400/642d2920-45c0-11e6-957d-b3ab5cd29fdc.png)

Update 1: The chart-json-edit directive doesn't work. No changes reflected on chart from editing the JSON.

**Comment by ashleydavis** [comment]
Can you provide a working version of the app that demonstrates the issue?

**Comment by PalakjainJain** [comment]
@Audace i am also getting the same problem ,any idea how to resolve this

**Comment by ashleydavis** [comment]
This repo still works out of the box. 

If you are having a problem it might be because you are using with a later version of AngularJS. Or maybe it's just a problem with the way you integrated it with your code.

I'm not planning on upgrading this repo, sorry. Please let me know if you find a fix for your problem.
