### ISSUE TITLE
can't detect $scope.chartViewModel.nodes[i]

### ISSUE THREAD

**Issue by sherysheng** [codecapers/AngularJS-FlowChart#30]
![workflow](https://cloud.githubusercontent.com/assets/18654503/25172621/2e0550cc-2524-11e7-9591-c01c571a6d15.jpg)

As show in the picture, each rect shows on the right side is referenced to a json format data in the left side.
Is it possible to add a “ng-click” event on each rect  and then trigger the related json data in the left side? (each rect represents a “$scope.chartViewModel.nodes[i]”).

**Comment by sherysheng** [comment]
@ashleydavis

**Comment by ashleydavis** [comment]
What do you mean by 'trigger the related json data'?

**Comment by sherysheng** [comment]
$scope.selectedWorkflow = {
			chartViewModel : {
				name : "",
				nodes : [],
				connections : []
			}
		};

I initialized a chartviewmodel , and there are some nodes[] in it .

And then every time the user click the "add new task" button , I save a new task into the nodes,
which the single node is something like below ,

			var newNodeDataModel = {
				name : $scope.selectedTask.name,
				id : newId,
				x : 0,
				y : 0,
				parameters : $scope.selectedTask.parameters,
				resources : [],
				inputConnectors : [ {
					name : "input"
				} ],
				outputConnectors : [ {
					name : "success"
				}, {
					name : "complete"
				}, {
					name : "failure"
				} ]
			
			$scope.selectedWorkflow.chartViewModel.nodes.push(newNodeDataModel); 

For the JSON data I mentioned is the key&value of every single node.
I was wondering  if I can add a "ng-click" on the "node" , because I want to trigger a panel or modal after I click on a task(a node) , and display the related json data in a better user friendly GUI , to let them modify and save this node's  values. 

Thanks!!

**Comment by sherysheng** [comment]
@ashleydavis

**Comment by ashleydavis** [comment]
Sure you can add an ng-click and trigger a panel or a modal. How you do that depends on what CSS framework you are using so I can't really comment on it.

You can display json in HTML with AngularJS as follows:

{{someJavaScriptObject | json}}

I'm pretty sure there is an example of that you can look at in the code.

Please note that I never intended for you to show json to an end user. The json data is only shown in my code example so that you as a developer can get a better idea of how it all works and what kind of data would be serialized, but I don't necessarily think it's a good idea to show the json to your user.

**Comment by sherysheng** [comment]
![image](https://cloud.githubusercontent.com/assets/18654503/25320735/0a603fcc-28dc-11e7-84ff-8fbb540e43c7.png)

Hi Ashley,
I just have below code in my html , it is when I click add a task in above picture (the "+" button) ,
I will push a new node into the $scope.selectedWorkflow.chartViewModel.nodes[i].

<section id="chartArea" style="height: 100%">
         <flow-chart style=" width: 100%; height:550px;" chart="chartViewModel"> </flow-chart>
 </section>


I already have a GUI to edit the value of the "node" , but my question is , how can I detect every single node I added , 
Because currently I can only use ng-repeat="node in chart.nodes"  and bind node.XXX to the html element to display all my nodes.
**But what I really need is to display the node which I clicked!** 
So how can I achieve this ?
Is there a way that I can listen to every node's mouseclick event?

**Comment by sherysheng** [comment]
@ashleydavis
