### ISSUE TITLE
hoverElement.scope() returns null issue.

### ISSUE THREAD

**Issue by Eiarzate1** [codecapers/AngularJS-FlowChart#31]
I have an issue with the function inside flowchart_directive.js

`//
	// Hit test and retreive node and connector that was hit at the specified coordinates.
	//
	this.checkForHit = function (mouseOverElement, whichClass) {

		//
		// Find the parent element, if any, that is a connector.
		//
		var hoverElement = this.searchUp(this.jQuery(mouseOverElement), whichClass);
		if (!hoverElement) {
			return null;
		}

		return hoverElement.scope();
	};`

hoverElement.scope() may return false if debug mode is not turned on.

AngularJS documentation states that in order for us to access element.scope() we must have debugging on.
In a production application this may not be a viable solution, due to the fact that a production system may not be deployed in "debug" mode for X reason.

https://docs.angularjs.org/api/ng/function/angular.element

I am still looking for an alternative to this but feel free to fix it or I will try to send a pull request.

Thank you.

**Comment by tomavic** [comment]
Is this project dead!!!

**Comment by PalakjainJain** [comment]
@Eiarzate1 did you get any solution for this problem,even i'am getting same error

**Comment by ashleydavis** [comment]
This isn't a live project. If you find  a fix please submit a pull  request.
