### ISSUE TITLE
Failed to load template: flowchart/flowchart_template.html (HTTP status: 404 Not Found)

### ISSUE THREAD

**Issue by fieldcommandergraeme** [codecapers/AngularJS-FlowChart#36]
I am running my application on IIS express via Visual Studio. When I navigate to index.html I receive the above error. What do I need to do to the configuration for the application to register the flowchart template?

**Comment by ashleydavis** [comment]
I don't use IIS so I can't help with that.

I just tested it with live-server (https://www.npmjs.com/package/live-server) and it works fine, so maybe the problem is with your IIS configuration.
